refactoring

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,4 +1,4 @@
-#!/bin/bash -e
+#!/bin/bash 
 
 #####################################
 #
@@ -15,12 +15,18 @@
 #
 #####################################
 
-if [ "$1" == "-h" ] || [ "$1" == "" ]; then 
-echo "command line help"
+if [ "$1" == "-h" ]; then 
+echo "Command line help:"
 echo ""
-echo "./setup.sh cluster-number api-server-port-number"
+echo "./install [cluster number or cluster name (Optional)] [api-server port number (Optional)]"
 echo ""
-echo "./setup.sh 1 6443"
+echo "Examples:"
+echo "1. Default:"
+echo "Optional:"
+echo "   ./install "
+echo "   ./install 1"
+echo "   ./install cluster1"
+echo "   ./install cluster1 6441"
 exit 0
 fi
 
@@ -29,20 +35,48 @@ if [ "$1" == "cleanup" ]; then
   exit 0
 fi
 
-#!/bin/bash
+export COLOR_PREFIX="\e"
+export ECHO_E="echo -e"
+if [ "$OS" == "Darwin" ]; then
+    export COLOR_PREFIX="\033"
+fi
+
+export DARKRED="\033[1;31m"
+export RED="\033[3;31m"
+export DARKGREEN="\033[1;32m"
+export GREEN="\033[3;32m"
+export DARKYELLOW="\033[1;33m"
+export YELLOW="\033[3;33m"
+export DARKBLUE="\033[1;34m"
+export BLUE="\033[3;34m"
+export DARKPURPLE="\033[1;35m"
+export PURPLE="\033[3;35m"
+export DARKTEAL="\033[1;36m"
+export TEAL="\033[3;36m"
+export DARKGRAY="\033[1;90m"
+export GRAY="\033[3;37m"
+export ENDCOLOR="\033[3;0m"
+export CANYON=${TEAL}
+
+export E_DARKRED="${COLOR_PREFIX}[1;31m"
+export E_RED="${COLOR_PREFIX}[3;31m"
+export E_DARKGREEN="${COLOR_PREFIX}[1;32m"
+export E_GREEN="${COLOR_PREFIX}[3;32m"
+export E_DARKYELLOW="${COLOR_PREFIX}[1;33m"
+export E_YELLOW="${COLOR_PREFIX}[3;33m"
+export E_DARKBLUE="${COLOR_PREFIX}[1;34m"
+export E_BLUE="${COLOR_PREFIX}[3;34m"
+export E_DARKPURPLE="${COLOR_PREFIX}[1;35m"
+export E_PURPLE="${COLOR_PREFIX}[3;35m"
+export E_DARKTEAL="${COLOR_PREFIX}[1;36m"
+export E_TEAL="${COLOR_PREFIX}[3;36m"
+export E_ENDCOLOR="${COLOR_PREFIX}[3;0m"
+
 WORKSPACE=${PWD}
 
 export KUBECONFIG=~/.kube/config
 export PATH=$PATH:${WORKSPACE}/bin
-CLUSTER_NAME="mesher"
 
-reg_port='5000'
-endpoint=''
-
-echo
-echo
-echo "An useful to create kind cluster that presented by Solarmesh"
-echo
 status=1
 spin="/-\|"
 #  while true; do
@@ -53,10 +87,24 @@ spin="/-\|"
 #  done 
 # exit  
 
+# prerequisites
+
+which kubectl > /dev/null
+if [[ $? != 0 ]]; then
+  echo "Please install kubectl first"
+  exit -1
+fi
+
+which kind > /dev/null
+if [[ $? != 0 ]]; then
+  echo "Please install KinD first"
+  exit -1
+fi
+
 user_memory=$(free | awk '{print $7}' | awk 'NR==2')
-min_memory=4091456
+min_memory=2048000
 if [[ ${user_memory} -lt ${min_memory} ]]; then
-  echo 'Error: At least 6G of available memory is required'
+  echo 'Error: At least 2G of available memory is required'
   exit 1
 fi
 
@@ -109,21 +157,35 @@ ip=${result}
 fi
 
 ip="${ip#"${ip%%[![:space:]]*}"}"
-echo ""
-echo "${ip}"
-echo ""
 
-cluster_num=$1
-cluster_name=cluster${cluster_num}
+cluster_num=$(kind get clusters | wc -l)
+cluster_num=$((cluster_num + 1))
 
-reg_name='kind-registry'
-reg_port='5000'
+cluster_name=$1
 
-INET='eth0'
+echo $1 | grep -q "^[0-9]*$"
+if [[ $? == 0 ]]; then
+  cluster_name=cluster${cluster_num}
+else
+  cluster_name=$1
+fi
+
+# check if cluster name is already exist
+if [[ $(kind get clusters | grep -cnw ${cluster_name}) -gt 0 ]]; then
+  echo "Error: ${cluster_name} is already exist!"
+  exit -1
+fi
+
+ip16=$(docker network inspect kind | grep Gateway | grep -v '::' | awk '{print $2}' | sed s/\"//g | sed s/.0.1//g)
+
+echo
+echo -e "${GREEN}Mercury is installing ${cluster_name} with virtual IP ${ip16}.25${cluster_num}.0/24 on host ${ip} ...${E_GREEN}"
+echo
+
+# reg_name='kind-registry'
+# reg_port='5000'
 
 work_dir="$PWD"
-#INGRESS_HOST=$(ifconfig ${INET} | grep -v inet6 | grep inet | awk '{print $2}')
-#echo ${INGRESS_HOST}
 
 # The default version of k8s under Linux is 1.18
 # https://github.com/solo-io/service-mesh-hub/issues/700
@@ -137,39 +199,48 @@ kindImage=kindest/node:v1.17.5
 # Create NodePort for remote cluster so it can be reachable from the management plane.
 # This config is roughly based on: https://kind.sigs.k8s.io/docs/user/ingress/
 function install_cluster() (
-
   kubeport=$2
+  if [[ "$2" == "" ]]; then
+    kubeport=644$1
+  fi 
 
   cat <<EOF | kind create cluster --name ${cluster_name} --image $kindImage --config=-
 kind: Cluster
 apiVersion: kind.x-k8s.io/v1alpha4
-#containerdConfigPatches:
-#- |-
-#  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${reg_port}"]
-#    endpoint = ["http://${reg_name}:${reg_port}"]
 networking:
   apiServerAddress: "${ip}"
-  apiServerPort: $kubeport
+  apiServerPort: ${kubeport}
+  kubeProxyMode: "ipvs"
 nodes:
-- role: control-plane   
-- role: worker      
-
+- role: control-plane
+- role: worker
+kubeadmConfigPatches:
+- |
+  apiVersion: kubeadm.k8s.io/v1beta2
+  kind: ClusterConfiguration
+  apiServer:
+    extraArgs:
+      service-account-api-audiences: "api,istio-ca"
+      service-account-signing-key-file: "/etc/kubernetes/pki/sa.key"
+      service-account-issuer: "kubernetes.default.svc"
 EOF
 
   wait
 
-  for node in $(kind get nodes); do
-    kubectl annotate node "${node}" "kind.x-k8s.io/registry=localhost:${reg_port}";
-  done
+  # for node in $(kind get nodes); do
+  #   kubectl annotate node "${node}" "kind.x-k8s.io/registry=localhost:${reg_port}";
+  # done
   printf "\n\n---\n"
   echo "Finished setting up ${cluster_name}"
 
 )
 
-if [[ $(kind get clusters | grep master | wc -l) < 1 ]]; then
+if [[ $(kind get clusters | grep ${cluster_name} | wc -l) < 1 ]]; then
 
 install_cluster $@
 
+# kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml
+# kubectl -n kube-system set env daemonset/calico-node FELIX_IGNORELOOSERPF=true
 fi
 
 cd "${work_dir}"
@@ -195,7 +266,8 @@ data:
     - name: default
       protocol: layer2
       addresses:
-      - "172.18.25${cluster_num}.1-172.18.25${cluster_num}.255"
+      - "${ip16}.25${cluster_num}.1-${ip16}172.18.25${cluster_num}.255"
 _EOF
 
-echo '✔ Clusters have been created'
+echo -e "${GREEN}✔${E_GREEN} Mercury have been created"
+
